"""
Domain models for the campaign world sub-domain.

CampaignWorld is a separate aggregate from Campaign. It holds the rich
D&D 5e setting generated by the narrator: settlement, factions, NPCs,
and adventure hooks. It links back to its campaign via campaign_id.

Separated from campaign models to keep Campaign focused on requirements intake.
"""

import logging
import uuid
from dataclasses import dataclass
from datetime import datetime

logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class Settlement:
    """The starting town or village where the campaign begins."""

    name: str
    population: int
    governance: str
    description: str


@dataclass(frozen=True)
class Faction:
    """A group of NPCs with shared goals operating in the campaign world."""

    name: str
    goals: str
    public_reputation: str
    # hidden_agenda is DM-only — never included in player-facing output
    hidden_agenda: str


@dataclass(frozen=True)
class CampaignNPC:
    """
    A key non-player character in the world.

    stat_block_ref is an optional string like "MM 2025 p.123 (CR 2)"
    for DM combat reference. secret is DM-only information.
    """

    name: str
    species: str
    role: str
    personality: str
    secret: str | None
    stat_block_ref: str | None


@dataclass(frozen=True)
class AdventureHook:
    """A single plot entry point tied to one of the Three Pillars of play."""

    # "combat", "exploration", or "social"
    pillar: str
    hook: str
    # Optional name of an NPC who delivers or is connected to this hook
    connected_npc: str | None


@dataclass(frozen=True)
class CampaignWorld:
    """
    Aggregate root for a generated campaign world.

    Created by CampaignNarratorPort.generate_world() and persisted by
    CampaignWorldRepository. Links back to its campaign via campaign_id.
    """

    world_id: uuid.UUID
    campaign_id: uuid.UUID
    world_name: str
    # premise is a 2-3 sentence spoiler-free pitch of the campaign's central premise
    premise: str
    starting_settlement: Settlement
    factions: tuple[Faction, ...]
    key_npcs: tuple[CampaignNPC, ...]
    central_conflict: str
    adventure_hooks: tuple[AdventureHook, ...]
    created_at: datetime
