"""
Domain models for the dungeons bounded context.

A Dungeon is one prepared session -- rooms, encounters, and a quest arc --
generated by an LLM from the selected World's lore and the Campaign's
requirements. Multiple Dungeons can exist per Campaign (one per session).

No SQLAlchemy or FastAPI imports belong here. Pure Python domain logic only.
"""

import logging
import uuid
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum

from app.dungeons.domain.exceptions import InvalidDungeonSettingsError

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

ROOM_COUNT_MIN = 5
ROOM_COUNT_MAX = 15
PARTY_SIZE_MIN = 1
PARTY_SIZE_MAX = 8


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------


class RoomType(str, Enum):
    """The function and encounter flavour of a single dungeon room."""

    COMBAT = "COMBAT"
    SHOP = "SHOP"
    REST = "REST"
    BOSS = "BOSS"
    TREASURE = "TREASURE"
    EVENT = "EVENT"


class EffectType(str, Enum):
    """The mechanical effect a GameEffect produces when triggered."""

    DAMAGE = "DAMAGE"
    HEAL = "HEAL"
    APPLY_STATUS = "APPLY_STATUS"
    GRANT_LOOT = "GRANT_LOOT"
    SPAWN_ENEMY = "SPAWN_ENEMY"
    UNLOCK_PATH = "UNLOCK_PATH"
    NONE = "NONE"


# ---------------------------------------------------------------------------
# Value Objects (frozen dataclasses -- immutable, identity-less)
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class DungeonSettings:
    """
    Describes the DM's per-session generation parameters.

    Validated on construction. difficulty_override allows the DM to adjust
    encounter difficulty for a specific session without changing the campaign.
    dm_notes are free-text hints appended to the LLM prompt.
    """

    campaign_id: uuid.UUID
    room_count: int
    party_size: int
    difficulty_override: str | None = None
    dm_notes: str | None = None

    def __post_init__(self) -> None:
        if not (ROOM_COUNT_MIN <= self.room_count <= ROOM_COUNT_MAX):
            raise InvalidDungeonSettingsError(
                f"room_count must be between {ROOM_COUNT_MIN} and {ROOM_COUNT_MAX}, "
                f"got {self.room_count}"
            )
        if not (PARTY_SIZE_MIN <= self.party_size <= PARTY_SIZE_MAX):
            raise InvalidDungeonSettingsError(
                f"party_size must be between {PARTY_SIZE_MIN} and {PARTY_SIZE_MAX}, "
                f"got {self.party_size}"
            )
        logger.debug(
            "DungeonSettings validated: campaign_id=%s rooms=%d party=%d",
            self.campaign_id,
            self.room_count,
            self.party_size,
        )


@dataclass(frozen=True)
class EnemyData:
    """
    Structured enemy information for a dungeon room.

    COMBAT rooms use initial + optional reinforcements.
    BOSS rooms add boss name and special_attacks.
    """

    initial: tuple[str, ...]
    reinforcements: tuple[str, ...]
    trigger_condition: str | None = None
    environmental_hazards: str | None = None
    boss: str | None = None
    special_attacks: tuple[str, ...] = ()


@dataclass(frozen=True)
class SkillCheck:
    """A single skill check within a room's mechanics."""

    # 'type' shadows the builtin but is the correct domain term here.
    type: str  # noqa: A003
    dc: int
    on_success: str
    on_failure: str | None = None


@dataclass(frozen=True)
class TriggerData:
    """
    Describes the action or check that fires a GameEffect.

    trigger_action is a domain-meaningful event name (e.g. "on_enemy_death").
    check_stat is the skill or ability used for the triggering roll, if any.
    dc is the Difficulty Class for the check; must be 1-30 when present.
    """

    trigger_action: str
    check_stat: str | None = None
    dc: int | None = None

    def __post_init__(self) -> None:
        if self.dc is not None and not (1 <= self.dc <= 30):
            raise InvalidDungeonSettingsError(
                f"TriggerData.dc must be between 1 and 30, got {self.dc}"
            )


@dataclass(frozen=True)
class GameEffect:
    """
    A discrete mechanical consequence attached to a room trigger.

    effect_type determines what happens when this effect fires.
    trigger describes the condition that fires it.
    value is a numeric magnitude (e.g. damage points, heal amount).
    status is a string identifier for status effects (APPLY_STATUS only).
    item_id is an identifier for granted loot (GRANT_LOOT only).
    """

    effect_type: EffectType
    trigger: TriggerData
    value: int | None = None
    status: str | None = None
    item_id: str | None = None


@dataclass(frozen=True)
class RoomMechanics:
    """
    Structured mechanical content for a room.

    skill_checks covers any room type. rest_benefit is populated for REST
    rooms. victory_items is populated for BOSS rooms.
    game_effects is an ordered tuple of structured mechanical consequences
    that trigger during play (US-071).
    """

    skill_checks: tuple[SkillCheck, ...]
    rest_benefit: str | None = None
    victory_items: tuple[str, ...] = ()
    game_effects: tuple[GameEffect, ...] = ()


@dataclass(frozen=True)
class LootItem:
    """A single loot entry in a TREASURE room's loot table."""

    item: str
    quantity: int
    value: str | None = None
    rarity: str | None = None


@dataclass(frozen=True)
class NpcInventoryItem:
    """An item sold or offered by an NPC in a SHOP room."""

    item: str
    price: int


@dataclass(frozen=True)
class NpcData:
    """
    Structured NPC information for a SHOP or EVENT room.

    interaction_dc is a dict mapping skill names to DC integers, with an
    optional 'note' key for context (e.g. {"Persuasion": 12, "note": "..."}).
    """

    name: str
    role: str
    inventory: tuple[NpcInventoryItem, ...]
    interaction_dc: dict[str, object] | None = None


@dataclass(frozen=True)
class QuestMetadata:
    """
    Session-wide quest metadata returned alongside the dungeon.

    recommended_level is an integer between 1 and 20.
    global_modifiers is a passive rule that applies to the entire dungeon.
    """

    name: str
    recommended_level: int
    environment: str
    global_modifiers: str


@dataclass(frozen=True)
class DungeonRoom:
    """
    A single room within a generated dungeon.

    index is 0-based. room_type determines the encounter flavour.

    Legacy flat fields (enemy_names, npc_names) are kept for backward
    compatibility when reading old JSON records. Structured fields
    (enemies, mechanics, loot_table, npc_data) replace them for newly
    generated dungeons.
    """

    index: int
    room_type: RoomType
    name: str
    description: str
    # Legacy flat fields -- empty by default on new records.
    enemy_names: tuple[str, ...] = ()
    npc_names: tuple[str, ...] = ()
    # Structured fields (US-063 to US-071).
    enemies: EnemyData | None = None
    mechanics: RoomMechanics | None = None
    loot_table: tuple[LootItem, ...] | None = None
    npc_data: tuple[NpcData, ...] | None = None


@dataclass(frozen=True)
class DungeonQuest:
    """
    The primary quest thread for a generated dungeon session.

    stages is an ordered tuple of narrative beat descriptions -- one per major
    milestone the party must reach to complete the session's quest.
    """

    name: str
    description: str
    stages: tuple[str, ...]


# ---------------------------------------------------------------------------
# Aggregate Root
# ---------------------------------------------------------------------------


@dataclass
class Dungeon:
    """
    Aggregate root for the dungeons bounded context.

    Generated by DungeonNarratorPort using World lore + Campaign settings.
    Persisted so the DM can review before starting a Room. One campaign can
    have many dungeons -- one per planned session.

    world_id is stored redundantly from Campaign for query convenience,
    so dungeon detail can be fetched without re-loading the campaign.

    current_room_index tracks which room the party is currently in (US-069).
    completed_stage_indices tracks which quest stages have been completed.
    quest_metadata holds session-wide metadata generated alongside the dungeon.
    """

    id: uuid.UUID
    campaign_id: uuid.UUID
    world_id: uuid.UUID
    name: str
    premise: str
    rooms: tuple[DungeonRoom, ...]
    quest: DungeonQuest
    created_at: datetime
    quest_metadata: QuestMetadata | None = None
    current_room_index: int = 0
    completed_stage_indices: list[int] = field(default_factory=list)

    def __post_init__(self) -> None:
        logger.debug(
            "Dungeon created: id=%s campaign_id=%s rooms=%d",
            self.id,
            self.campaign_id,
            len(self.rooms),
        )
