"""
Domain models for the dungeons bounded context.

A Dungeon is one prepared session — rooms, encounters, and a quest arc —
generated by an LLM from the selected World's lore and the Campaign's
requirements. Multiple Dungeons can exist per Campaign (one per session).

No SQLAlchemy or FastAPI imports belong here. Pure Python domain logic only.
"""

import logging
import uuid
from dataclasses import dataclass
from datetime import datetime
from enum import Enum

from app.dungeons.domain.exceptions import InvalidDungeonSettingsError

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

ROOM_COUNT_MIN = 5
ROOM_COUNT_MAX = 15
PARTY_SIZE_MIN = 1
PARTY_SIZE_MAX = 8


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------


class RoomType(str, Enum):
    """The function and encounter flavour of a single dungeon room."""

    COMBAT = "COMBAT"
    SHOP = "SHOP"
    REST = "REST"
    BOSS = "BOSS"
    TREASURE = "TREASURE"
    EVENT = "EVENT"


# ---------------------------------------------------------------------------
# Value Objects (frozen dataclasses — immutable, identity-less)
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class DungeonSettings:
    """
    Describes the DM's per-session generation parameters.

    Validated on construction. difficulty_override allows the DM to adjust
    encounter difficulty for a specific session without changing the campaign.
    dm_notes are free-text hints appended to the LLM prompt.
    """

    campaign_id: uuid.UUID
    room_count: int
    party_size: int
    difficulty_override: str | None = None
    dm_notes: str | None = None

    def __post_init__(self) -> None:
        if not (ROOM_COUNT_MIN <= self.room_count <= ROOM_COUNT_MAX):
            raise InvalidDungeonSettingsError(
                f"room_count must be between {ROOM_COUNT_MIN} and {ROOM_COUNT_MAX}, "
                f"got {self.room_count}"
            )
        if not (PARTY_SIZE_MIN <= self.party_size <= PARTY_SIZE_MAX):
            raise InvalidDungeonSettingsError(
                f"party_size must be between {PARTY_SIZE_MIN} and {PARTY_SIZE_MAX}, "
                f"got {self.party_size}"
            )
        logger.debug(
            "DungeonSettings validated: campaign_id=%s rooms=%d party=%d",
            self.campaign_id,
            self.room_count,
            self.party_size,
        )


@dataclass(frozen=True)
class DungeonRoom:
    """
    A single room within a generated dungeon.

    index is 0-based. room_type determines the encounter flavour.
    enemy_names and npc_names are tuples (immutable sequences) of display names.
    """

    index: int
    room_type: RoomType
    name: str
    description: str
    enemy_names: tuple[str, ...]
    npc_names: tuple[str, ...]
    special_notes: str | None = None


@dataclass(frozen=True)
class DungeonQuest:
    """
    The primary quest thread for a generated dungeon session.

    stages is an ordered tuple of narrative beat descriptions — one per major
    milestone the party must reach to complete the session's quest.
    """

    name: str
    description: str
    stages: tuple[str, ...]


# ---------------------------------------------------------------------------
# Aggregate Root
# ---------------------------------------------------------------------------


@dataclass
class Dungeon:
    """
    Aggregate root for the dungeons bounded context.

    Generated by DungeonNarratorPort using World lore + Campaign settings.
    Persisted so the DM can review before starting a Room. One campaign can
    have many dungeons — one per planned session.

    world_id is stored redundantly from Campaign for query convenience,
    so dungeon detail can be fetched without re-loading the campaign.
    """

    id: uuid.UUID
    campaign_id: uuid.UUID
    world_id: uuid.UUID
    name: str
    premise: str
    rooms: tuple[DungeonRoom, ...]
    quest: DungeonQuest
    created_at: datetime

    def __post_init__(self) -> None:
        logger.debug(
            "Dungeon created: id=%s campaign_id=%s rooms=%d",
            self.id,
            self.campaign_id,
            len(self.rooms),
        )
